apiVersion: v1
data:
  mapAccounts: '[]'
  mapRoles: '[{"rolearn":"arn:aws:iam::437377620726:role/KubernetesStack-arbitrarybitseksclusterMastersRole-EGOHO9P7J8NI","username":"arn:aws:iam::437377620726:role/KubernetesStack-arbitrarybitseksclusterMastersRole-EGOHO9P7J8NI","groups":["system:masters"]}]'
  mapUsers: |
    - userarn: arn:aws:iam::437377620726:user/admin
      username: admin
      groups:
        - eks-console-dashboard-full-access-group
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapAccounts":"[]","mapRoles":"[{\"rolearn\":\"arn:aws:iam::437377620726:role/KubernetesStack-arbitrarybitseksclusterMastersRole-EGOHO9P7J8NI\",\"username\":\"arn:aws:iam::437377620726:role/KubernetesStack-arbitrarybitseksclusterMastersRole-EGOHO9P7J8NI\",\"groups\":[\"system:masters\"]}]","mapUsers":"[]"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"aws.cdk.eks/prune-c88949cf318e417d1a0d55327f9908059e6f76bfe2":""},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-01-12T09:22:21Z"
  labels:
    aws.cdk.eks/prune-c88949cf318e417d1a0d55327f9908059e6f76bfe2: ""
  name: aws-auth
  namespace: kube-system
  resourceVersion: "35859"
  uid: e9aa9283-d4a3-4da7-bdbd-832314d15c14